server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/bermudezEstefania
  application:
    name: ms-users

final:
  keycloak:
    serverUrl: http://localhost:8090/
    realm: bermudezEstefania
    clientId: final-client
    clientSecret: bgJSAB2zOA8LGwclPuaA4dLKavlu1JlB

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka